### ISSUE TITLE
Link between branch point and child not drawn in 2D canvas

### ISSUE THREAD

**Issue by carshadi** [morphonets/SNT#81]
Links between branch points and their children are not drawn in the 2D canvas as of version 4.0.6

![image](https://user-images.githubusercontent.com/44130022/148600005-b0671ba5-425c-4ac3-baf4-28fb251cec91.png)
**To Reproduce**
File > Load Tracings > Remote Databases > NeuroMorpho... and load neuron with ID VGlut-F-400787

**Comment by tferr** [comment]
OOps. Not sure why I did not notice it. I only tried with the OP_1 demo. Will look

**Comment by tferr** [comment]
@carshadi, I think 29a32b0 fixes this. If you have a chance, could you please double-check?

**Comment by carshadi** [comment]
It is fixed on my end 🙌

**Comment by tferr** [comment]
@carshadi , I am reopening this as I just noticed that things are still not fixed in Reconstruction Viewer (and likely not in scivew):

Left is the same neuron (VGlut-F-400787) in rec viewer, right the ImagePlus canvas:
![image](https://user-images.githubusercontent.com/2439948/150619323-676c8941-8656-4ecc-850b-b885edcf06dd.png)

**Comment by tferr** [comment]
The issue here was that the bulk of the nodes for that cell (the same for all FlyCircuit SWCs?)  are tagged as 'Soma' and were never rendered as polylines. We probably should implement an option to ignore SWC type flags on import, as there are too many cases of weird tags everywhere. Closing for now.
